//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public string MessageType { get; set; }
        public string MessageContent { get; set; }
        public string Recipient { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
