//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskQueue
    {
        public int QueueId { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> EnqueuedAt { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
