//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvanceFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public string Package { get; set; }
        public Nullable<int> QueueID { get; set; }
    
        public virtual Queue Queue { get; set; }
    }
}
