//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ProyectoFinal.Data
{
    public partial class TaskSummary
    {
        public string Status { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
