//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLog
    {
        public int LogId { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> ExecutionStart { get; set; }
        public Nullable<System.DateTime> ExecutionEnd { get; set; }
        public Nullable<bool> Success { get; set; }
        public string ErrorMessage { get; set; }
        public string LogDetails { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
